=== Borjarguez/filmsProject/FilmsProyect/cines.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT cinemas (cinema)+>
<!ATTLIST cinemas
  xmlns CDATA #FIXED ''>

<!ELEMENT cinema (company,num_Pictures_Theatre,location,billboard)>
<!ATTLIST cinema
  xmlns CDATA #FIXED ''
  name CDATA #REQUIRED>

<!ELEMENT company (#PCDATA)>
<!ATTLIST company
  xmlns CDATA #FIXED ''>

<!ELEMENT num_Pictures_Theatre (num_Regular_Pictures_Theatres,
                                num_3D_Pictures_Theatres)>
<!ATTLIST num_Pictures_Theatre
  xmlns CDATA #FIXED ''>

<!ELEMENT location (longitude,latitude)>
<!ATTLIST location
  xmlns CDATA #FIXED ''>

<!ELEMENT billboard (available_Movies)>
<!ATTLIST billboard
  xmlns CDATA #FIXED ''>

<!ELEMENT num_Regular_Pictures_Theatres (#PCDATA)>
<!ATTLIST num_Regular_Pictures_Theatres
  xmlns CDATA #FIXED ''>

<!ELEMENT num_3D_Pictures_Theatres (#PCDATA)>
<!ATTLIST num_3D_Pictures_Theatres
  xmlns CDATA #FIXED ''>

<!ELEMENT longitude (#PCDATA)>
<!ATTLIST longitude
  xmlns CDATA #FIXED ''>

<!ELEMENT latitude (#PCDATA)>
<!ATTLIST latitude
  xmlns CDATA #FIXED ''>

<!ELEMENT available_Movies (title,age_Rating,schedule)>
<!ATTLIST available_Movies
  xmlns CDATA #FIXED ''>

<!ELEMENT title (#PCDATA)>
<!ATTLIST title
  xmlns CDATA #FIXED ''>

<!ELEMENT age_Rating (#PCDATA)>
<!ATTLIST age_Rating
  xmlns CDATA #FIXED ''>

<!ELEMENT schedule (hour)+>
<!ATTLIST schedule
  xmlns CDATA #FIXED ''>

<!ELEMENT hour (#PCDATA)>
<!ATTLIST hour
  xmlns CDATA #FIXED ''>

=== Borjarguez/filmsProject/FilmsProyect/cines.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cinemas SYSTEM "cines.dtd">
<cinemas>
    <cinema name="Cinesa de intu Asturias">
        <company>Cinesa</company>
        <num_Pictures_Theatre>
            <num_Regular_Pictures_Theatres>14</num_Regular_Pictures_Theatres>
            <num_3D_Pictures_Theatres>3</num_3D_Pictures_Theatres>
        </num_Pictures_Theatre>
        <location>
            <longitude>-5.804771</longitude>
            <latitude>43.389570</latitude>
        </location>
        <billboard>
            <available_Movies>
                <title>Cementerio de animales</title>
                <age_Rating>+16</age_Rating>
                <schedule>
                    <hour>15:50</hour>
                    <hour>22:35</hour>
                </schedule>
            </available_Movies>
        </billboard>
    </cinema>

    <cinema name="Yelmo Cines">
        <company>Yelmo</company>
        <num_Pictures_Theatre>
            <num_Regular_Pictures_Theatres>11</num_Regular_Pictures_Theatres>
            <num_3D_Pictures_Theatres>2</num_3D_Pictures_Theatres>
        </num_Pictures_Theatre>
        <location>
            <longitude>-5.697158</longitude>
            <latitude>43.535785</latitude>
        </location>
        <billboard>
            <available_Movies>
                <title>Vengadores: Endgame</title>
                <age_Rating>+13</age_Rating>
                <schedule>
                    <hour>16:00</hour>
                    <hour>17:00</hour>
                    <hour>20:00</hour>
                </schedule>
            </available_Movies>
        </billboard>
    </cinema>

</cinemas>
