=== Borjarguez/filmsProject/FilmsProyect/films.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT films (film)+>
<!ATTLIST films
  xmlns CDATA #FIXED ''>

<!ELEMENT film (genre,director,filming_date,duration,film_production,
                (resumen|summary),actors,awards)>
<!ATTLIST film
  xmlns CDATA #FIXED ''
  title CDATA #REQUIRED>

<!ELEMENT genre (#PCDATA)>
<!ATTLIST genre
  xmlns CDATA #FIXED ''>

<!ELEMENT director (name,surname,born)>
<!ATTLIST director
  xmlns CDATA #FIXED ''>

<!ELEMENT filming_date (#PCDATA)>
<!ATTLIST filming_date
  xmlns CDATA #FIXED ''>

<!ELEMENT duration (#PCDATA)>
<!ATTLIST duration
  xmlns CDATA #FIXED ''>

<!ELEMENT film_production (name,main_employees)>
<!ATTLIST film_production
  xmlns CDATA #FIXED ''>

<!ELEMENT resumen (#PCDATA)>
<!ATTLIST resumen
  xmlns CDATA #FIXED ''>

<!ELEMENT summary (#PCDATA)>
<!ATTLIST summary
  xmlns CDATA #FIXED ''>

<!ELEMENT actors (actor)+>
<!ATTLIST actors
  xmlns CDATA #FIXED ''>

<!ELEMENT awards (award)+>
<!ATTLIST awards
  xmlns CDATA #FIXED ''>

<!ELEMENT born (#PCDATA)>
<!ATTLIST born
  xmlns CDATA #FIXED ''>

<!ELEMENT main_employees ((name,surname,position)|employee+)>
<!ATTLIST main_employees
  xmlns CDATA #FIXED ''>

<!ELEMENT actor (surname,date_birth,place_birth,photos,filmography)>
<!ATTLIST actor
  xmlns CDATA #FIXED ''
  name NMTOKEN #REQUIRED>

<!ELEMENT award (actor_name?,date)>
<!ATTLIST award
  xmlns CDATA #FIXED ''
  name CDATA #REQUIRED>

<!ELEMENT employee (name,surname,position)>
<!ATTLIST employee
  xmlns CDATA #FIXED ''>

<!ELEMENT date_birth (#PCDATA)>
<!ATTLIST date_birth
  xmlns CDATA #FIXED ''>

<!ELEMENT place_birth (#PCDATA)>
<!ATTLIST place_birth
  xmlns CDATA #FIXED ''>

<!ELEMENT photos (image)+>
<!ATTLIST photos
  xmlns CDATA #FIXED ''>

<!ELEMENT filmography (#PCDATA)>
<!ATTLIST filmography
  xmlns CDATA #FIXED ''>

<!ELEMENT actor_name (#PCDATA)>
<!ATTLIST actor_name
  xmlns CDATA #FIXED ''>

<!ELEMENT date (#PCDATA)>
<!ATTLIST date
  xmlns CDATA #FIXED ''>

<!ELEMENT image EMPTY>
<!ATTLIST image
  xmlns CDATA #FIXED ''
  url CDATA #REQUIRED>

<!ELEMENT name (#PCDATA)>
<!ATTLIST name
  xmlns CDATA #FIXED ''>

<!ELEMENT surname (#PCDATA)>
<!ATTLIST surname
  xmlns CDATA #FIXED ''>

<!ELEMENT position (#PCDATA)>
<!ATTLIST position
  xmlns CDATA #FIXED ''>

=== Borjarguez/filmsProject/FilmsProyect/films.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE films SYSTEM "films.dtd">
<?xml-stylesheet type="text/xsl" href="premios.xsl"?>
<films>
  <film title ="Los vengadores">
    <genre>Action</genre>
    <director>
      <name>Joss</name>
      <surname>Whedon</surname>
      <born>New York, US</born>
    </director>
    <filming_date>July 2010</filming_date>
    <duration>143 minutes</duration>
    <film_production>
      <name>Marvel Studios</name>
      <main_employees>
        <name>Kevin</name>
        <surname>Feige</surname>
        <position>Producer</position>
      </main_employees>
    </film_production>
    <summary>American superhero film based on the Marvel Comics superhero team </summary>
    <actors>
      <actor name="Robert">
        <surname>John Downey Jr.</surname>
        <date_birth>April 4, 1965</date_birth>
        <place_birth>New York</place_birth>
        <photos>
          <image url="https://en.wikipedia.org/wiki/Robert_Downey_Jr.#/media/File:Robert_Downey_Jr_2014_Comic_Con_(cropped).jpg"></image>
          <image url="https://revistadiners.com.co/wp-content/uploads/2019/04/robertdowneyjr_800x669.jpg"></image>
          <image url="http://www.californiamuseum.org/sites/main/files/imagecache/lightbox/main-images/robertdowneyjr_cahalloffameinductee.png"></image>
        </photos>
        <filmography>Iron Man, The Avengers, Sherlock Holmes</filmography>
      </actor>

      <actor name="Chris">
        <surname>Evans</surname>
        <date_birth>June 13, 1981</date_birth>
        <place_birth>Boston, US</place_birth>
        <photos>
          <image url="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/5_Dec._2016_CJCS_USO_Holiday_Tour_-_Incirlik_Air_Base_161205-D-PB383-044_%2831430825446%29_%28cropped%29_%28cropped%29.jpg/330px-5_Dec._2016_CJCS_USO_Holiday_Tour_-_Incirlik_Air_Base_161205-D-PB383-044_%2831430825446%29_%28cropped%29_%28cropped%29.jpg"></image>
          <image url="https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Chris_Evans_-_Captain_America_2_press_conference_%28cropped%29.jpg/255px-Chris_Evans_-_Captain_America_2_press_conference_%28cropped%29.jpg"></image>
          <image url="https://telefuturo.com.py/system/news_images/images/000/018/478/big/chris-evans.jpg?1556569128"></image>
        </photos>
        <filmography>Fantastic Four, Captain America, The Avengers</filmography>
      </actor>

      <actor name="Mark">
        <surname>Ruffalo</surname>
        <date_birth>November 22, 1967</date_birth>
        <place_birth>Kenosha, Wisconsin</place_birth>
        <photos>
          <image url="https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Mark_Ruffalo_in_2017_by_Gage_Skidmore.jpg/330px-Mark_Ruffalo_in_2017_by_Gage_Skidmore.jpg"></image>
          <image url="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQDESZ3RR_u9vgBRVX5s-UAdJirPlyz1RqcbTg-nUg2246v5VC"></image>
          <image url="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3FiCS0MRHgLJ22FloX3jPxLNFKEzR9JQiN3Qrro7dG4g4bJxSlg"></image>
        </photos>
        <filmography>Zodiac, Blindness, The Avengers</filmography>
      </actor>

      <actor name="Chris">
        <surname>Hemsworth</surname>
        <date_birth>11 August 1983</date_birth>
        <place_birth>	Phillip Island, Victoria, Australia</place_birth>
        <photos>
          <image url="https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Chris_Hemsworth_by_Gage_Skidmore.jpg/330px-Chris_Hemsworth_by_Gage_Skidmore.jpg"></image>
          <image url="https://heroichollywood.com/wp-content/uploads/2019/03/Avengers_Endgame_Chris_Hemsworth_Thor.jpg"></image>
          <image url="https://i.pinimg.com/236x/e1/77/e1/e177e1a64164cbe07a277a6f4d1de605.jpg"></image>
        </photos>
        <filmography>Thor, The Avengers, Men in Black</filmography>
      </actor>

      <actor name="Scarlett">
        <surname>Johansson</surname>
        <date_birth>November 22, 1984</date_birth>
        <place_birth>New York, US</place_birth>
        <photos>
          <image url="https://www.hola.com/imagenes/belleza/caraycuerpo/20190308138623/fitness-entrenamiento-scarlett-johansson-adaptar-horario-mc/0-656-376/scarlet-johansson-en-forma-m.jpg?interpolation=lanczos-normal&amp;downsize=0.75xw:*&amp;output-format=progressive-jpeg&amp;output-quality=70"></image>
          <image url="https://ep01.epimg.net/elpais/imagenes/2017/02/15/estilo/1487163010_132182_1487163367_noticia_normal.jpg"></image>
          <image url="https://specials-images.forbesimg.com/imageserve/5b44fc1ea7ea4341970e27fd/416x416.jpg?background=000000&amp;cropX1=1516&amp;cropX2=4451&amp;cropY1=156&amp;cropY2=3092"></image>
        </photos>
        <filmography>Lucy, The Avengers, Ghost in the shell</filmography>
      </actor>

      <actor name="Jeremy">
        <surname>Renner</surname>
        <date_birth>January 7, 1971</date_birth>
        <place_birth>Modesto, California, US</place_birth>
        <photos>
          <image url="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Jeremy_Renner_SDCC_2014_crop.jpg/330px-Jeremy_Renner_SDCC_2014_crop.jpg"></image>
          <image url="https://pixel.nymag.com/imgs/daily/vulture/2017/04/17/17-jermey-renner.w700.h700.jpg"></image>
          <image url="https://vignette.wikia.nocookie.net/avengers-infinity-war-parte-1-y-2/images/0/0b/Jeremy-Renner.jpg/revision/latest?cb=20180225182013&amp;path-prefix=es"></image>
        </photos>
        <filmography>The Avengers, Tag, The Town</filmography>
      </actor>

    </actors>
    <awards>
      <award name="Mejor Actor">
        <actor_name>Robert Downey Jr.</actor_name>
        <date>2013</date>
      </award>

      <award name="Mejor Actor de Accion">
        <actor_name>Chris Hemsworth</actor_name>
        <date>2013</date>
      </award>

      <award name="Superheroe Favorito de la Pelicula">
        <actor_name>Robert Downey Jr.</actor_name>
        <date>2013</date>
      </award>
    </awards>
  </film>

  <film title ="Titanic">
    <genre>Drama</genre>
    <director>
      <name>James</name>
      <surname>Cameron</surname>
      <born> Kapuskasing, Canada</born>
    </director>
    <filming_date>September 1996</filming_date>
    <duration>195 min</duration>
    <film_production>
      <name>Fox</name>
      <main_employees>
        <employee>
          <name>James</name>
          <surname>Cameron</surname>
          <position>Director</position>
        </employee>

        <employee>
          <name>Jon</name>
          <surname>Landau</surname>
          <position>Producer</position>
        </employee>
      </main_employees>
    </film_production>
    <resumen>American epic romance and disaster film. It narrates the story of members of different social classes who fall in love aboard the ship during its ill-fated maiden voyage.</resumen>
    <actors>
      <actor name="Leonardo">
        <surname>Di Caprio</surname>
        <date_birth>November 11, 1974</date_birth>
        <place_birth>Los Angeles, California, U.S.</place_birth>
        <photos>
          <image url="https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Leonardo_DiCaprio_visited_Goddard_Saturday_to_discuss_Earth_science_with_Piers_Sellers_%2826105091624%29_cropped.jpg/330px-Leonardo_DiCaprio_visited_Goddard_Saturday_to_discuss_Earth_science_with_Piers_Sellers_%2826105091624%29_cropped.jpg"></image>
          <image url="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Leonardo_DiCaprio_October_2016.jpg/220px-Leonardo_DiCaprio_October_2016.jpg"></image>
          <image url="https://www.rollingstone.com/wp-content/uploads/2018/06/rs-196159-102997242.jpg?crop=900:600&amp;width=440"></image>
        </photos>
        <filmography>Poison Ivy, Titanic, The Wolf of Wall Street</filmography>
      </actor>

      <actor name="Kate">
        <surname>Winslet</surname>
        <date_birth>5 October, 1975</date_birth>
        <place_birth>Reading, Berkshire, England</place_birth>
        <photos>
          <image url="https://www.lecturas.com/medio/2017/07/28/kate-winslet_cba91129_800x490.jpg"></image>
          <image url="https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/kate-winslet-winner-of-the-dilys-powell-award-for-news-photo-911471296-1555514211.jpg?crop=1.00xw:0.672xh;0,0&amp;resize=480:*"></image>
          <image url="https://ewedit.files.wordpress.com/2017/12/mcdtita_fe018.jpg"></image>
        </photos>
        <filmography>Titanic, The Reader, Divergent</filmography>
      </actor>

    </actors>
    <awards>
      <award name="Oscar a la mejor pelicula">
        <date>1998</date>
      </award>

      <award name="Oscar al mejor director">
        <actor_name>James Cameron</actor_name>
        <date>1998</date>
      </award>
    </awards>
  </film>

  <film title ="Iron Man 3">
    <genre>Action</genre>
    <director>
      <name>Shane</name>
      <surname>Black</surname>
      <born>Pittsburgh, Pensilvania, Estados Unidos</born>
    </director>
    <filming_date>May 23, 2012</filming_date>
    <duration>131 min</duration>
    <film_production>
      <name>Marvel Studios</name>
      <main_employees>
        <employee>
          <name>Kevin</name>
          <surname>Feige</surname>
          <position>Producer</position>
        </employee>
      </main_employees>
    </film_production>
    <summary>American superhero film based on the Marvel Comics character Iron Man</summary>
    <actors>
      <actor name="Robert">
        <surname>John Downey Jr.</surname>
        <date_birth>April 4, 1965</date_birth>
        <place_birth>New York</place_birth>
        <photos>
          <image url="https://en.wikipedia.org/wiki/Robert_Downey_Jr.#/media/File:Robert_Downey_Jr_2014_Comic_Con_(cropped).jpg"></image>
          <image url="https://revistadiners.com.co/wp-content/uploads/2019/04/robertdowneyjr_800x669.jpg"></image>
